// todo-app/todo-app-react/src/components/TodoItem.js
import React from 'react';

export default function TodoItem({
  items,
  deleteTodoItem,
  completeTodoItem,
  updateTodoItem,
}) {
  const [modelIndex, setModelIndex] = React.useState(0);
  const [title, setTitle] = React.useState('');
  const [description, setDescription] = React.useState('');
  function renderTodoList(items) {
    return items.map((item, index) => {
      return (
        <tr key={index}>
          <th>{item.title}</th>
          <th>{item.description}</th>
          <th>{item.date}</th>
          <th>{item.status}</th>
          <th>
            <div className='btns'>
              <button onClick={() => completeTodoItem(index)}>
                {item.status === 'Active' ? 'Complete' : 'Active'}
              </button>
              <button
                data-toggle='modal'
                data-target='#exampleModal'
                onClick={() => {
                  setModelIndex(index);
                  setTitle(item.title);
                  setDescription(item.description);
                }}
              >
                Update
              </button>
              <button onClick={() => deleteTodoItem(index)}>X</button>
            </div>
          </th>
        </tr>
      );
    });
  }
  function editTodo(modelIndex) {
    return (
      <>
        <div
          className='modal fade'
          id='exampleModal'
          tabIndex='-1'
          role='dialog'
          aria-labelledby='exampleModalLabel'
          aria-hidden='true'
        >
          <div className='modal-dialog' role='document'>
            <div className='modal-content'>
              <div className='modal-header'>
                <h5 className='modal-title text-dark' id='exampleModalLabel'>
                  Update Todo
                </h5>
                <button
                  type='button'
                  className='close'
                  data-dismiss='modal'
                  aria-label='Close'
                >
                  <span aria-hidden='true'>&times;</span>
                </button>
              </div>
              <div className='modal-body'>
                <div className='form-group'>
                  <label
                    htmlFor='recipient-name'
                    className='col-form-label text-dark'
                  >
                    Title:
                  </label>
                  <input
                    type='text'
                    className='form-control'
                    id='recipient-name'
                    defaultValue={items[modelIndex].title || ''}
                    onChange={(e) => setTitle(e.target.value)}
                  />
                </div>
                <div className='form-group'>
                  <label
                    htmlFor='message-text'
                    className='col-form-label text-dark'
                  >
                    Description:
                  </label>
                  <textarea
                    className='form-control'
                    id='message-text'
                    defaultValue={items[modelIndex].description || ''}
                    onChange={(e) => setDescription(e.target.value)}
                  ></textarea>
                </div>
              </div>
              <div className='modal-footer'>
                <button
                  type='button'
                  className='btn btn-secondary'
                  data-dismiss='modal'
                >
                  Close
                </button>
                <button
                  type='button'
                  className='btn btn-primary'
                  onClick={() => updateTodoItem(modelIndex, title, description)}
                >
                  Update
                </button>
              </div>
            </div>
          </div>
        </div>
      </>
    );
  }
  return (
    <>
      <table className='table'>
        <thead>
          <tr>
            <th scope='col'>Title</th>
            <th scope='col'>Description</th>
            <th scope='col'>Date</th>
            <th scope='col'>Status</th>
            <th scope='col'>Action</th>
          </tr>
        </thead>
        <tbody>{renderTodoList(items)}</tbody>
      </table>
      {items.length ? editTodo(modelIndex) : ''}
    </>
  );
}

// todo-app/todo-app-angular/src/app/component/todo-item/todo-item.component.ts
import { Component, OnInit } from '@angular/core';
import { Item } from 'src/app/model/item';
import { TodoListService } from 'src/app/service/todo-list.service';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.scss'],
})
export class TodoItemComponent implements OnInit {
  todoList: any;
  constructor(private todoListService: TodoListService) {}

  ngOnInit(): void {
    this.todoList = this.todoListService.getTodoList();
  }
  item = { title: '', description: '', date: '', status: '' };
  changeIndex(index: any): void {
    this.item = this.todoList[index];
  }
  addItem(item: any): void {
    const d = new Date();
    const date =
      (d.getDate() < 10 ? '0' + d.getDate() : d.getDate()) +
      '/' +
      d.getMonth() +
      '/' +
      d.getFullYear();
    this.todoList = this.todoListService.addItem({
      title: item.title,
      description: item.description,
      date: date,
      status: 'Active',
    });
  }
  updateItem(item: any) {
    console.log(item);
    if (item.title == '' || item.title == null) item.title = this.item.title;
    if (item.description == '' || item.description == null)
      item.description = this.item.description;
    let changes: Item = {
      title: item.title,
      description: item.description,
      date: this.item.date,
      status: this.item.status,
    };
    this.todoList = this.todoListService.updateItem(this.item, changes);
  }

  completeTodoItem(index: any) {
    let change = this.todoList[index];
    if (this.todoList[index].status === 'Active') {
      change.status = 'Completed';
    } else {
      change.status = 'Active';
    }
    this.todoList = this.todoListService.updateItem(
      this.todoList[index],
      change
    );
  }

  deleteTodoItem(index: any) {
    this.todoList = this.todoListService.deleteItem(this.todoList[index]);
  }
}

<div class='mb-3 d-flex justify-content-center'>
  <form #itemForm="ngForm" (ngSubmit)="addItem(itemForm.value)">
    <input class="m-2 p-1" name='title' ngModel type='text' placeholder='Create todo' />
    <input class="m-2 p-1" name='description' ngModel type='text' placeholder='Description todo' />
    <button class="p-1" type="submit">Create</button>
  </form>
</div>
<div class=" mb-3">
  <table class='table'>
    <thead>
      <tr>
        <th scope='col'>Title</th>
        <th scope='col'>Description</th>
        <th scope='col'>Date</th>
        <th scope='col'>Status</th>
        <th scope='col'>Action</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let item of todoList;let i = index">
        <th>{{item.title}}</th>
        <th>{{item.description}}</th>
        <th>{{item.date}}</th>
        <th>{{item.status}}</th>
        <th>
          <div class='btns'>
            <button (click)="completeTodoItem(i)" class="mb-1 px-1">
              {{item.status === 'Active' ? 'Completed' : 'Active'}}
            </button>
            <button class="mb-1 px-1" data-toggle='modal' data-target='#exampleModal' (click)="changeIndex(i)">
              Update
            </button>
            <button class="mb-1 px-1" (click)="deleteTodoItem(i)">X</button>
          </div>
        </th>
      </tr>
    </tbody>
  </table>
</div>
<form class='modal fade' id='exampleModal' tabIndex='-1' role='dialog' aria-labelledby='exampleModalLabel'
  aria-hidden='true' #itemFormUpdate="ngForm" (ngSubmit)="updateItem(itemFormUpdate.value)">
  <div class='modal-dialog' role='document'>
    <div class='modal-content'>
      <div class='modal-header'>
        <h5 class='modal-title text-dark' id='exampleModalLabel'>
          Update Todo
        </h5>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
          <span aria-hidden='true'>&times;</span>
        </button>
      </div>
      <div class='modal-body'>
        <div class='form-group'>
          <label htmlFor='recipient-name' class='col-form-label text-dark'>
            Title:
          </label>
          <input type='text' class='form-control' id='recipient-name' ngModel name='title' [value]="item.title" />
        </div>
        <div class='form-group'>
          <label htmlFor='message-text' class='col-form-label text-dark'>
            Description:
          </label>
          <textarea class='form-control' id='message-text' ngModel name="description"
            [value]="item.description"></textarea>
        </div>
      </div>
      <div class='modal-footer'>
        <button type='button' class='btn btn-secondary' data-dismiss='modal'>
          Close
        </button>
        <button type='submit' class='btn btn-primary'>
          Update
        </button>
      </div>
    </div>
  </div>
</form>
